export interface Config {
    maxPlayers?: number, // Max players per game instance (MAX: 81) (done)
    maxConnectionsPerIP?: number, // Max connections per IP address (done)
    startingScore?: number, // Default amount of score each player spawns with (done)
    maxHealth?: number, // Max health a player can have/heal to (MAX: 100) (done)
    maxSpeed?: number, // Max base speed for players (done)
    allowLevelOneUpgrades?: boolean, // Allow level one upgrades to be equipped (done)
    allowLevelTwoUpgrades?: boolean, // Allow level two upgrades to be equipped (done)
    allowLevelThreeUpgrades?: boolean, // Allow level three upgrades to be equipped (done)
    allowLevelOneArmor?: boolean, // Allow level one armor (done)
    allowLevelTwoArmor?: boolean, // Allow level two armor (done)
    allowLevelThreeArmor?: boolean, // Allow level three armor (done)
    noMidPerkTimeout?: boolean, // Toggle timeout for mid perk (done)
    damageMultplier?: number, // Damage multiplier applied to every gun (done)
    rangeMultiplier?: number, // Range multiplier applied to every gun (done)
    bulletSpeedMultiplier?: number, // Bullet speed multiplier applied to every bullet (done)
    fogEnabled?: boolean, // Enable fog for the game instance (done)
    fogSize?: number, // Custom starting fog size (MAX: 7000 - MIN: 2000) (done)
    fogDamagePerTick?: number, // Fog damage to players per tick (MAX: 100) (done)
    scoreSquareEnabled?: boolean, // Enable score square for game instance (only for FFA) (done)
    scoreSquareGain?: number, // Score gain inside score square (done)
    randomSpawnsEnabled?: boolean, // Enable random spawn positions around the map (inside fog if enabled)
    healthRegenPerTick?: number, // Health regenerated every tick (MAX: 100) (done)
    armorRegenPerTick?: number, // Armor regenerated per tick (MAX: 30) (done)
    bottomlessMags?: boolean, // Enable infinite amo (done)
    bulletDamageEnabled?: boolean, // Enable bullet damage to players (done)
    customNamesEnabled?: boolean // Enable custom player names
    playerCollisionsEnabled?: boolean // Enable player collisions (done)
    bulletCollisionsEnabled?: boolean // Enable bullet collisions with players (done)
    premiumCratesEnabled?: boolean // Enable premium crates for the game instance (done)
}